---
data_root_path : "/media/hdd1/dataset/"
dataset_path: "/media/hdd1/dy_project/dataset/" # preprocessed data path
model_path: "/media/hdd1/dy/model/"
preprocess:
  flag: false
  analyze : false
  chunk_size: 4
  datasets:
fit:
  flag: true
  meta:
    flag: false
    inner_optim: adam
    inner_loss: mse
    inner_lr: 0.01
  model: DeepPhys
  time_length: 64
  overlap_interval : 32 # default 0
  img_size: 64
  train:
    flag: true
    dataset: UBFC
    shuffle: true
    fs: 30 #video fps
    batch_size: 100
    learning_rate: 0.001
    epochs: 1
    loss: mse
    optimizer: adam
  val:
    flag: true
    dataset: UBFC
    shuffle: true
    interval: 1 # min 1
    fs: 30 #video fps
    batch_size: 100
  test:
    flag: true
    metric: ['MAE','RMSE','MAPE','Pearson']
    dataset: UBFC
    shuffle: false
    interval: 20 # test interval epoch
    fs: 30 #video fps
    batch_size: 100


